/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrackJobIdRouteImport } from './routes/track.$jobId'
import { Route as AdminStagesRouteImport } from './routes/admin.stages'
import { Route as AdminSapRouteImport } from './routes/admin.sap'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackJobIdRoute = TrackJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => TrackRoute,
} as any)
const AdminStagesRoute = AdminStagesRouteImport.update({
  id: '/admin/stages',
  path: '/admin/stages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSapRoute = AdminSapRouteImport.update({
  id: '/admin/sap',
  path: '/admin/sap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRouteWithChildren
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sap': typeof AdminSapRoute
  '/admin/stages': typeof AdminStagesRoute
  '/track/$jobId': typeof TrackJobIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRouteWithChildren
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sap': typeof AdminSapRoute
  '/admin/stages': typeof AdminStagesRoute
  '/track/$jobId': typeof TrackJobIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRouteWithChildren
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sap': typeof AdminSapRoute
  '/admin/stages': typeof AdminStagesRoute
  '/track/$jobId': typeof TrackJobIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/track'
    | '/admin/customers'
    | '/admin/documents'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/sap'
    | '/admin/stages'
    | '/track/$jobId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/track'
    | '/admin/customers'
    | '/admin/documents'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/sap'
    | '/admin/stages'
    | '/track/$jobId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/track'
    | '/admin/customers'
    | '/admin/documents'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/sap'
    | '/admin/stages'
    | '/track/$jobId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  TrackRoute: typeof TrackRouteWithChildren
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSapRoute: typeof AdminSapRoute
  AdminStagesRoute: typeof AdminStagesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$jobId': {
      id: '/track/$jobId'
      path: '/$jobId'
      fullPath: '/track/$jobId'
      preLoaderRoute: typeof TrackJobIdRouteImport
      parentRoute: typeof TrackRoute
    }
    '/admin/stages': {
      id: '/admin/stages'
      path: '/admin/stages'
      fullPath: '/admin/stages'
      preLoaderRoute: typeof AdminStagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sap': {
      id: '/admin/sap'
      path: '/admin/sap'
      fullPath: '/admin/sap'
      preLoaderRoute: typeof AdminSapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TrackRouteChildren {
  TrackJobIdRoute: typeof TrackJobIdRoute
}

const TrackRouteChildren: TrackRouteChildren = {
  TrackJobIdRoute: TrackJobIdRoute,
}

const TrackRouteWithChildren = TrackRoute._addFileChildren(TrackRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  TrackRoute: TrackRouteWithChildren,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSapRoute: AdminSapRoute,
  AdminStagesRoute: AdminStagesRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
